title: Traveling HPC Maker-more-effient-er
description: Random musings
author: David Ressman
github: https://github.com/davidr
about: mild-mannered hpc guy for a major metropolitan financial firm
disqus_shortname: davidressman
google_analytics: UA-66618872-3

enableTags: true
tagarray: []

social:
    - icon: fa-twitter
      link: "https://twitter.com/davidressman"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ressman"

share:
  twitter_username: davidressman

urls:
    - text: About Me
      url: /about/
    - text: CV
      url: /cv/
    - text: Github
      url: https://github.com/davidr

url: "https://davidr.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - octopress-minify-html
